import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import FooterB2c from "../components/FooterB2c";
import React from "react";
import Link from "next/link";

const Search: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Welcome home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href="/"><a>Home</a></Link>
            <Link href="/search"><a>Search</a></Link>

            <main className={styles.main}>
                <FooterB2c userName={'Nobody'} />
            </main>

        </div>
    )
}

export default Search
